//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPricing
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string Slab_range { get; set; }
        public Nullable<double> Slab_range_price_per_unit { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
